# Triggered on a new release git tag pushed, starts the final steps of a release.
#
# Steps currently include
#   1. Cherry-pick changelogs, change history, and other doc updates to master

name: Finalize Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'release/*'

jobs:
  finalize:
    name: Cherry-pick Changelogs to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo test
      - name: Set Git Config
        run: |
          git config --local user.email 38288322+imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      - name: Switch to master
        run: git checkout --track origin/master
      - name: Cherry-pick changelogs
        run: |
          git cherry-pick $commitid

          # Clean up files that we don't want to cherry-pick changes back
          for i in **/package.json; do git checkout --ours $i; done
          git checkout --ours **/version-policies.json docs/changehistory/NextVersion.md

          # Stage explicit files;
          #   - Files resolved due to taking master's version
          #   - All changelogs to remove duplicates from master
          #     - They would be duplicated if the same PR is backported to the release branch
          git add **/package.json **/version-policies.json common/changes docs/changehistory/NextVersion.md

          commitMessage=$(git log --format=%B -n 1 $commitid)

          # Git commit should fail if there are outstanding conflicts
          git commit -m "$commitMessage Changelogs"

          rush change --bulk --message "" --bump-type none
          git add .
          git commit --amend --no-edit
        env:
          commitid: ${{ github.sha }}
      - name: Push to master
        run: git push https://$(GITHUBTOKEN)@github.com/imodeljs/imodeljs HEAD:master
